# Generated by Django 4.0.6 on 2022-07-15 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
